"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./psle-science.module.css";
import { questions, sprintPlan, topics, type Question, type Topic } from "./question-bank";

type QuizMode = "daily" | "mock" | "weak" | "topic" | "trap";
type Screen = "home" | "quiz" | "topics" | "plan" | "journal" | "resources";

type Attempt = { questionId:string; topicId:string; correct:boolean; guessed:boolean; selectedIndex:number; at:string };
type JournalEntry = { id:string; questionId:string; topicId:string; concept:string; prompt:string; selected:string; correct:string; explanation:string; trap:string; at:string };
type SavedProgress = { startDate:string; attempts:Attempt[]; journal:JournalEntry[] };

const STORAGE_KEY = "futureplus-psle-science-mcq-coach-v1";

function isoDate(date = new Date()) { return date.toISOString().slice(0, 10); }
function shuffle<T>(items:T[]):T[] { const copy=[...items]; for(let i=copy.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];} return copy; }
function daysBetween(a:string,b:string){const first=new Date(`${a}T00:00:00`);const second=new Date(`${b}T00:00:00`);return Math.max(0,Math.floor((second.getTime()-first.getTime())/86_400_000));}
function formatTimer(seconds:number){const minutes=Math.floor(seconds/60).toString().padStart(2,"0");const secs=(seconds%60).toString().padStart(2,"0");return `${minutes}:${secs}`;}
function masteryLabel(score:number,attempts:number){if(attempts===0)return "Not tested";if(score>=0.9&&attempts>=4)return "Secure";if(score>=0.75)return "Nearly there";return "Rescue";}

export default function PSLEScienceCoach(){
  const [screen,setScreen]=useState<Screen>("home");
  const [progress,setProgress]=useState<SavedProgress>({startDate:isoDate(),attempts:[],journal:[]});
  const [hydrated,setHydrated]=useState(false);
  const [quiz,setQuiz]=useState<Question[]>([]);
  const [mode,setMode]=useState<QuizMode>("daily");
  const [questionIndex,setQuestionIndex]=useState(0);
  const [selectedIndex,setSelectedIndex]=useState<number|null>(null);
  const [checked,setChecked]=useState(false);
  const [unsure,setUnsure]=useState(false);
  const [sessionAnswers,setSessionAnswers]=useState<Attempt[]>([]);
  const [timerSeconds,setTimerSeconds]=useState(45*60);
  const [sessionFinished,setSessionFinished]=useState(false);
  const [toast,setToast]=useState("");

  useEffect(()=>{try{const saved=window.localStorage.getItem(STORAGE_KEY);if(saved)setProgress(JSON.parse(saved) as SavedProgress);}catch{}finally{setHydrated(true);}},[]);
  useEffect(()=>{if(!hydrated)return;try{window.localStorage.setItem(STORAGE_KEY,JSON.stringify(progress));}catch{}},[progress,hydrated]);
  useEffect(()=>{if(screen!=="quiz"||mode!=="mock"||sessionFinished)return;if(timerSeconds<=0){setSessionFinished(true);return;}const id=window.setInterval(()=>setTimerSeconds(v=>v-1),1000);return()=>window.clearInterval(id);},[screen,mode,timerSeconds,sessionFinished]);
  useEffect(()=>{if(!toast)return;const id=window.setTimeout(()=>setToast(""),2200);return()=>window.clearTimeout(id);},[toast]);

  const topicStats=useMemo(()=>topics.map(topic=>{const attempts=progress.attempts.filter(a=>a.topicId===topic.id);const secureCorrect=attempts.filter(a=>a.correct&&!a.guessed).length;const score=attempts.length?secureCorrect/attempts.length:0;return{...topic,attempts:attempts.length,score,secureCorrect};}),[progress.attempts]);
  const overall=useMemo(()=>{const attempts=progress.attempts;const correct=attempts.filter(a=>a.correct).length;const secure=attempts.filter(a=>a.correct&&!a.guessed).length;const studyDates=new Set(attempts.map(a=>a.at.slice(0,10))).size;const mastered=topicStats.filter(t=>t.score>=0.9&&t.attempts>=4).length;return{accuracy:attempts.length?correct/attempts.length:0,secureAccuracy:attempts.length?secure/attempts.length:0,attempts:attempts.length,studyDates,mastered};},[progress.attempts,topicStats]);
  const weakTopics=useMemo(()=>[...topicStats].sort((a,b)=>a.score-b.score||a.attempts-b.attempts).slice(0,4),[topicStats]);
  const sprintDay=useMemo(()=>Math.min(18,daysBetween(progress.startDate,isoDate())+1),[progress.startDate]);
  const todayPlan=sprintPlan[sprintDay-1]??sprintPlan[sprintPlan.length-1];
  const currentQuestion=quiz[questionIndex];
  const sessionCorrect=sessionAnswers.filter(a=>a.correct).length;

  function weightedDailyQuestions(count:number){
    const attemptsByQuestion=new Map<string,Attempt[]>();
    progress.attempts.forEach(attempt=>{const list=attemptsByQuestion.get(attempt.questionId)??[];list.push(attempt);attemptsByQuestion.set(attempt.questionId,list);});
    const scored=questions.map(question=>{const attempts=attemptsByQuestion.get(question.id)??[];const misses=attempts.filter(a=>!a.correct||a.guessed).length;const last=attempts.at(-1);const recency=last?daysBetween(last.at.slice(0,10),isoDate()):99;const priority=attempts.length===0?100:misses*20+Math.min(recency,10)-attempts.length;return{question,priority:priority+Math.random()*5};});
    const selected:Question[]=[];const usedTopics=new Map<string,number>();
    for(const item of scored.sort((a,b)=>b.priority-a.priority)){if(selected.length>=count)break;const used=usedTopics.get(item.question.topicId)??0;if(used<2){selected.push(item.question);usedTopics.set(item.question.topicId,used+1);}}
    if(selected.length<count)selected.push(...shuffle(questions.filter(q=>!selected.some(s=>s.id===q.id))).slice(0,count-selected.length));
    return shuffle(selected);
  }

  function startQuiz(nextMode:QuizMode,topicId?:string){
    let nextQuestions:Question[]=[];
    if(nextMode==="mock")nextQuestions=shuffle(questions).slice(0,30);
    if(nextMode==="daily")nextQuestions=weightedDailyQuestions(12);
    if(nextMode==="trap")nextQuestions=shuffle(questions.filter(q=>q.difficulty!=="foundation")).slice(0,15);
    if(nextMode==="topic"&&topicId)nextQuestions=shuffle(questions.filter(q=>q.topicId===topicId));
    if(nextMode==="weak"){const ids=weakTopics.map(t=>t.id);nextQuestions=shuffle(questions.filter(q=>ids.includes(q.topicId))).slice(0,12);}
    setMode(nextMode);setQuiz(nextQuestions);setQuestionIndex(0);setSelectedIndex(null);setChecked(false);setUnsure(false);setSessionAnswers([]);setSessionFinished(false);setTimerSeconds(45*60);setScreen("quiz");window.scrollTo({top:0,behavior:"smooth"});
  }

  function checkAnswer(){
    if(selectedIndex===null||!currentQuestion||checked)return;
    const correct=selectedIndex===currentQuestion.correctIndex;const now=new Date().toISOString();const attempt:Attempt={questionId:currentQuestion.id,topicId:currentQuestion.topicId,correct,guessed:unsure,selectedIndex,at:now};
    setSessionAnswers(existing=>[...existing,attempt]);
    setProgress(existing=>{const nextJournal=!correct||unsure?[{id:`${currentQuestion.id}-${now}`,questionId:currentQuestion.id,topicId:currentQuestion.topicId,concept:currentQuestion.concept,prompt:currentQuestion.stem,selected:currentQuestion.options[selectedIndex],correct:currentQuestion.options[currentQuestion.correctIndex],explanation:currentQuestion.explanation,trap:currentQuestion.trap,at:now},...existing.journal.filter(entry=>entry.questionId!==currentQuestion.id).slice(0,99)]:existing.journal;return{...existing,attempts:[...existing.attempts,attempt].slice(-1500),journal:nextJournal};});
    setChecked(true);
  }

  function nextQuestion(){if(questionIndex>=quiz.length-1){setSessionFinished(true);window.scrollTo({top:0,behavior:"smooth"});return;}setQuestionIndex(i=>i+1);setSelectedIndex(null);setChecked(false);setUnsure(false);window.scrollTo({top:0,behavior:"smooth"});}
  function buildJournalText(){return["PSLE Science MCQ Learning Journal",`Generated: ${new Date().toLocaleString()}`,"",...progress.journal.flatMap((entry,index)=>[`${index+1}. ${entry.concept}`,`Question: ${entry.prompt}`,`My answer: ${entry.selected}`,`Correct answer: ${entry.correct}`,`Concept fix: ${entry.explanation}`,`Trap to avoid: ${entry.trap}`,""])].join("\n");}
  async function copyJournal(){try{await navigator.clipboard.writeText(buildJournalText());setToast("Learning journal copied — paste into Google Keep, Docs or Notes.");}catch{setToast("Copy was blocked by the browser. Try Export instead.");}}
  function exportJournal(){const blob=new Blob([buildJournalText()],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`PSLE-Science-MCQ-Learning-Journal-${isoDate()}.txt`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);setToast("Learning journal exported.");}
  function resetProgress(){if(!window.confirm("Reset all MCQ progress and the learning journal on this browser?"))return;const fresh={startDate:isoDate(),attempts:[],journal:[]};setProgress(fresh);try{window.localStorage.removeItem(STORAGE_KEY);}catch{}setToast("Progress reset.");setScreen("home");}

  if(!hydrated)return <main className={styles.app}><div className={styles.loading}>Preparing your Science mission…</div></main>;

  return <main className={styles.app}>
    {toast&&<div className={styles.toast}>{toast}</div>}
    <div className={styles.shell}>
      <header className={styles.appHeader}>
        <button className={styles.logoButton} onClick={()=>setScreen("home")} aria-label="Go to MCQ Mission Control"><span className={styles.logoMark}>🔬</span><span><strong>Science MCQ Mission</strong><small>Future Plus · PSLE 2026 · AL1 target practice</small></span></button>
        <nav className={styles.nav} aria-label="Science coach navigation"><button className={screen==="home"?styles.navActive:""} onClick={()=>setScreen("home")}>Mission</button><button className={screen==="topics"?styles.navActive:""} onClick={()=>setScreen("topics")}>18 Topics</button><button className={screen==="plan"?styles.navActive:""} onClick={()=>setScreen("plan")}>18-Day Sprint</button><button className={screen==="journal"?styles.navActive:""} onClick={()=>setScreen("journal")}>Mistake Lab</button></nav>
      </header>

      {screen==="home"&&<>
        <section className={styles.hero}><div><span className={styles.eyebrow}>MCQ-FIRST SELF LEARNING</span><h1>Turn every wrong answer into a Science advantage.</h1><p className={styles.heroText}>A focused 2–3 week system for a strong Science student who knows the content but loses MCQ marks to distractors, rushed reading or hidden misconceptions.</p><div className={styles.heroActions}><button className={styles.primaryButton} onClick={()=>startQuiz("daily")}>Start today’s 12-question mission →</button><button className={styles.secondaryButton} onClick={()=>startQuiz("mock")}>Take a 30-question timed mock</button></div><p className={styles.privacyLine}>🔒 No sign-in. No child profile. Progress stays on this browser.</p></div><div className={styles.targetCard}><span className={styles.targetTop}>TODAY · DAY {sprintDay}</span><strong>{todayPlan.title}</strong><p>{todayPlan.task}</p><div className={styles.targetFocus}>{todayPlan.focus}</div><button onClick={()=>setScreen("plan")}>See the full sprint</button></div></section>
        <section className={styles.statsGrid}><Stat label="Questions attempted" value={String(overall.attempts)} note="Quality attempts, not question volume"/><Stat label="Raw accuracy" value={`${Math.round(overall.accuracy*100)}%`} note="Correct including uncertain guesses"/><Stat label="Secure accuracy" value={`${Math.round(overall.secureAccuracy*100)}%`} note="Correct and confidently reasoned"/><Stat label="Topics secure" value={`${overall.mastered}/18`} note={`${overall.studyDates} active study day${overall.studyDates===1?"":"s"}`}/></section>
        <section className={styles.methodSection}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>THE MCQ HABIT</span><h2>Predict → Eliminate → Prove</h2></div><p>Do not ask “Which option looks familiar?” Ask “Which option survives the evidence?”</p></div><div className={styles.methodGrid}><Method number="1" title="Read the stem" text="Notice NOT, best, most likely, based on results, which change."/><Method number="2" title="Predict first" text="Say the answer in your own words before options influence you."/><Method number="3" title="Eliminate" text="Reject contradictions, ignored conditions, partial truths and irrelevant facts."/><Method number="4" title="Prove it" text="If you cannot explain why it answers the exact question, mark ‘I’m not sure’."/></div></section>
        <section className={styles.missionGrid}><Mission icon="🎯" title="Daily Mission" text="Adaptive 12-question set that resurfaces missed, guessed and not-yet-tested concepts." action="Start adaptive set" onClick={()=>startQuiz("daily")}/><Mission icon="🚑" title="Weak Spot Rescue" text="Automatically concentrates questions from the four least-secure syllabus topics." action="Repair weak spots" onClick={()=>startQuiz("weak")}/><Mission icon="🧠" title="Distractor Trap Lab" text="Application questions: partial truths, irrelevant facts, swapped cause-effect and over-generalisation." action="Train trap detection" onClick={()=>startQuiz("trap")}/><Mission icon="⏱️" title="Booklet A Simulation" text="30 original MCQs with a 45-minute practice timer to build accuracy under exam pace." action="Start 30-question mock" onClick={()=>startQuiz("mock")}/></section>
        <section className={styles.weakSection}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>AUTO-DIAGNOSIS</span><h2>Your current rescue queue</h2></div><button className={styles.textButton} onClick={()=>setScreen("topics")}>View all 18 topics →</button></div><div className={styles.weakGrid}>{weakTopics.map(topic=><TopicMini key={topic.id} topic={topic} onClick={()=>startQuiz("topic",topic.id)}/>)}</div></section>
        <section className={styles.examNote}><div><span>2026 FORMAT</span><strong>30 MCQs · 60 marks</strong></div><p>The current Standard PSLE Science paper places 60% of the marks in Booklet A. This coach treats MCQ accuracy as a trainable reasoning skill—not “easy marks” to rush through.</p><button onClick={()=>setScreen("resources")}>Sources & further practice</button></section>
      </>}

      {screen==="quiz"&&currentQuestion&&!sessionFinished&&<section className={styles.quizWrap}><div className={styles.quizTopbar}><button className={styles.backButton} onClick={()=>setScreen("home")}>← Exit</button><div className={styles.progressTrack}><span style={{width:`${((questionIndex+(checked?1:0))/quiz.length)*100}%`}}/></div><strong>{questionIndex+1} / {quiz.length}</strong>{mode==="mock"&&<span className={timerSeconds<300?styles.timerDanger:styles.timer}>⏱ {formatTimer(timerSeconds)}</span>}</div><div className={styles.quizCard}><div className={styles.quizMeta}><span>{topics.find(t=>t.id===currentQuestion.topicId)?.icon} {topics.find(t=>t.id===currentQuestion.topicId)?.shortTitle}</span><span>{currentQuestion.concept}</span><span className={styles.difficulty}>{currentQuestion.difficulty}</span></div><h2>{currentQuestion.stem}</h2><div className={styles.options}>{currentQuestion.options.map((option,index)=>{let className=styles.option;if(selectedIndex===index)className+=` ${styles.optionSelected}`;if(checked&&index===currentQuestion.correctIndex)className+=` ${styles.optionCorrect}`;if(checked&&selectedIndex===index&&index!==currentQuestion.correctIndex)className+=` ${styles.optionWrong}`;return <button key={`${currentQuestion.id}-${index}`} className={className} disabled={checked} onClick={()=>setSelectedIndex(index)}><span>{String.fromCharCode(65+index)}</span><p>{option}</p></button>;})}</div>{!checked&&<div className={styles.answerBar}><label className={styles.unsureToggle}><input type="checkbox" checked={unsure} onChange={e=>setUnsure(e.target.checked)}/><span>🤔 I’m not sure / I’m guessing</span></label><button className={styles.primaryButton} disabled={selectedIndex===null} onClick={checkAnswer}>Check my reasoning</button></div>}{checked&&<div className={selectedIndex===currentQuestion.correctIndex?styles.feedbackCorrect:styles.feedbackWrong}><div className={styles.feedbackTitle}><span>{selectedIndex===currentQuestion.correctIndex?(unsure?"🟡":"✅"):"🧩"}</span><div><strong>{selectedIndex===currentQuestion.correctIndex?(unsure?"Correct — but keep this in the rescue queue":"Secure answer"):"This is a useful mistake"}</strong><p>Correct answer: <b>{String.fromCharCode(65+currentQuestion.correctIndex)}. {currentQuestion.options[currentQuestion.correctIndex]}</b></p></div></div><div className={styles.explainBox}><span>CONCEPT FIX</span><p>{currentQuestion.explanation}</p></div><div className={styles.trapBox}><span>EXAMINER-STYLE TRAP</span><p>{currentQuestion.trap}</p></div>{(!sessionAnswers.at(-1)?.correct||sessionAnswers.at(-1)?.guessed)&&<p className={styles.autoSaved}>📌 Saved automatically to Mistake Lab for spaced review.</p>}<button className={styles.primaryButton} onClick={nextQuestion}>{questionIndex===quiz.length-1?"Finish session":"Next question →"}</button></div>}</div></section>}

      {screen==="quiz"&&sessionFinished&&<section className={styles.results}><span className={styles.resultIcon}>{sessionCorrect/Math.max(sessionAnswers.length,1)>=0.9?"🏆":"🧭"}</span><span className={styles.eyebrow}>SESSION COMPLETE</span><h1>{sessionCorrect}/{sessionAnswers.length||quiz.length}</h1><p className={styles.resultLead}>{sessionCorrect/Math.max(sessionAnswers.length,1)>=0.9?"Excellent accuracy. Now make sure the correct answers were reasoned, not guessed.":"The score is diagnostic. The valuable part is the misconception trail you now know how to repair."}</p><div className={styles.resultStats}><div><strong>{Math.round((sessionCorrect/Math.max(sessionAnswers.length,1))*100)}%</strong><span>raw session accuracy</span></div><div><strong>{sessionAnswers.filter(a=>a.correct&&!a.guessed).length}</strong><span>secure answers</span></div><div><strong>{sessionAnswers.filter(a=>!a.correct||a.guessed).length}</strong><span>items added/reinforced in Mistake Lab</span></div></div><div className={styles.heroActions}><button className={styles.primaryButton} onClick={()=>startQuiz("weak")}>Repair weak spots now</button><button className={styles.secondaryButton} onClick={()=>setScreen("journal")}>Review Mistake Lab</button><button className={styles.textButton} onClick={()=>setScreen("home")}>Back to Mission Control</button></div></section>}

      {screen==="topics"&&<section className={styles.pageSection}><PageIntro eyebrow="FULL 2026 SYLLABUS MAP" title="All 18 PSLE Science topics, visible in one place" text="A topic becomes Secure only after repeated confident accuracy. Correct guesses do not count as secure mastery."/><div className={styles.topicGrid}>{topicStats.map(topic=><article className={styles.topicCard} key={topic.id}><div className={styles.topicCardTop}><span className={styles.topicIcon}>{topic.icon}</span><span className={styles.levelBadge}>{topic.level} · {topic.theme}</span></div><h3>{topic.shortTitle}</h3><p>{topic.title}</p><div className={styles.masteryLine}><span><i style={{width:`${Math.round(topic.score*100)}%`}}/></span><strong>{Math.round(topic.score*100)}%</strong></div><small>{masteryLabel(topic.score,topic.attempts)} · {topic.attempts} attempts</small><ul>{topic.coverage.map(item=><li key={item}>{item}</li>)}</ul><button onClick={()=>startQuiz("topic",topic.id)}>Run concept check →</button></article>)}</div></section>}

      {screen==="plan"&&<section className={styles.pageSection}><PageIntro eyebrow="2–3 WEEK LEARNING PACK" title="18-Day MCQ Accuracy Sprint" text="Designed for a student whose Science understanding is already strong: less passive revision, more diagnosis → explanation → spaced re-test → timed application."/><div className={styles.planNotice}><strong>Today is Sprint Day {sprintDay}.</strong><span>{todayPlan.title}: {todayPlan.task}</span></div><div className={styles.planGrid}>{sprintPlan.map(item=><article key={item.day} className={`${styles.planCard} ${item.day===sprintDay?styles.planToday:""}`}><span>DAY {item.day}</span><h3>{item.title}</h3><strong>{item.task}</strong><p>{item.focus}</p></article>)}</div><div className={styles.parentNote}><h3>Parent coaching rule</h3><p>Do not ask only “How many did you get right?” Ask: <b>“Which wrong option was tempting, and why is it wrong?”</b> A student who can explain the distractor has usually fixed the misconception.</p></div></section>}

      {screen==="journal"&&<section className={styles.pageSection}><PageIntro eyebrow="SPACED ERROR REVIEW" title="Mistake Lab" text="Every incorrect answer and every ‘I’m not sure’ correct answer is saved here. Re-read the concept fix, then retest the topic instead of memorising the option letter."/><div className={styles.journalActions}><button className={styles.primaryButton} onClick={copyJournal} disabled={!progress.journal.length}>Copy for Google Keep / Docs / Notes</button><button className={styles.secondaryButton} onClick={exportJournal} disabled={!progress.journal.length}>Export learning journal</button><button className={styles.textButton} onClick={resetProgress}>Reset local progress</button></div>{!progress.journal.length?<div className={styles.emptyState}><span>🧪</span><h3>Your Mistake Lab is empty.</h3><p>Start a Daily Mission. Mistakes and uncertain answers will appear here automatically.</p><button onClick={()=>startQuiz("daily")}>Start first mission</button></div>:<div className={styles.journalList}>{progress.journal.map(entry=>{const topic=topics.find(item=>item.id===entry.topicId);return <article className={styles.journalCard} key={entry.id}><div className={styles.journalMeta}><span>{topic?.icon} {topic?.shortTitle}</span><span>{entry.concept}</span></div><h3>{entry.prompt}</h3><p className={styles.myWrong}>My answer: {entry.selected}</p><p className={styles.correctText}>Correct: {entry.correct}</p><div className={styles.explainBox}><span>CONCEPT FIX</span><p>{entry.explanation}</p></div><div className={styles.trapBox}><span>TRAP</span><p>{entry.trap}</p></div><button onClick={()=>startQuiz("topic",entry.topicId)}>Retest this topic →</button></article>;})}</div>}</section>}

      {screen==="resources"&&<section className={styles.pageSection}><PageIntro eyebrow="TRUSTED RESOURCE SHELF" title="Use the official syllabus for scope, past papers for calibration, and coaching resources for technique" text="Official PSLE questions are copyrighted, so this app uses original questions rather than copying past papers or proprietary tuition-centre packs."/><div className={styles.resourceGrid}><Resource label="OFFICIAL" title="SEAB 2026 PSLE examination formats" text="Confirm the current Science paper structure and subject code." href="https://www.seab.gov.sg/psle/psle-formats-examined-in-2026/"/><Resource label="OFFICIAL" title="MOE 2023 Primary Science syllabus" text="The source-of-truth coverage map for Primary 3 to Primary 6." href="https://www.moe.gov.sg/-/media/files/primary/syllabus/2023-primary-science.ashx"/><Resource label="OFFICIAL" title="Authorised past-year paper distributors" text="Use legally published PSLE papers for final exam calibration." href="https://www.seab.gov.sg/distributors-of-past-years-question-papers/"/><Resource label="TECHNIQUE" title="EduFirst MCQ elimination strategies" text="Public guidance on eliminating distractors and reviewing wrong answers." href="https://www.edufirst.com.sg/blog/psle-science-mcq-proven-elimination-strategies-that-work/"/><Resource label="TECHNIQUE" title="BlueTree misconception and mind-map approach" text="Public explanation of misconception notebooks and precise question reading." href="https://www.bluetreeeducation.com/bluetree-psle-science-answering-strategies-why-children-lose-marks/"/><Resource label="REVISION PROGRAMME" title="The Pique Lab P6 revision programme" text="Example of a specialist programme built around conceptual pitfalls and review." href="https://thepiquelab.com/p6-science/erp-plus/"/></div><div className={styles.disclaimerBox}><strong>How to combine these with this app</strong><p>Use official or purchased past papers once or twice a week. After marking, identify every MCQ mistake by topic and use Mistake Lab to repair the misconception. The app’s job is the correction loop; the past paper’s job is calibration.</p></div></section>}

      <footer className={styles.appFooter}><p><strong>Science MCQ Mission</strong> is a Future Plus family learning tool. It is not affiliated with or endorsed by MOE, SEAB or any tuition provider.</p><p>72 original practice questions · browser-only progress · coverage aligned to the Primary Science syllabus used for PSLE Science from 2026.</p></footer>
    </div>
  </main>;
}

function Stat({label,value,note}:{label:string;value:string;note:string}){return <article className={styles.statCard}><span>{label}</span><strong>{value}</strong><p>{note}</p></article>;}
function Method({number,title,text}:{number:string;title:string;text:string}){return <article className={styles.methodCard}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>;}
function Mission({icon,title,text,action,onClick}:{icon:string;title:string;text:string;action:string;onClick:()=>void}){return <article className={styles.missionCard}><span className={styles.missionIcon}>{icon}</span><h3>{title}</h3><p>{text}</p><button onClick={onClick}>{action} →</button></article>;}
function TopicMini({topic,onClick}:{topic:Topic&{attempts:number;score:number};onClick:()=>void}){return <button className={styles.topicMini} onClick={onClick}><span>{topic.icon}</span><div><strong>{topic.shortTitle}</strong><small>{masteryLabel(topic.score,topic.attempts)} · {Math.round(topic.score*100)}%</small></div><b>→</b></button>;}
function PageIntro({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className={styles.pageIntro}><span className={styles.eyebrow}>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>;}
function Resource({label,title,text,href}:{label:string;title:string;text:string;href:string}){return <a className={styles.resourceCard} href={href} target="_blank" rel="noreferrer"><span>{label}</span><h3>{title}</h3><p>{text}</p><b>Open resource ↗</b></a>;}
