export type Difficulty = "foundation" | "application" | "challenge";

export type Question = {
  id: string;
  topicId: string;
  concept: string;
  difficulty: Difficulty;
  stem: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
  trap: string;
};

export type Topic = {
  id: string;
  level: "P3" | "P4" | "P5" | "P6";
  theme: "Diversity" | "Cycles" | "Systems" | "Energy" | "Interactions";
  title: string;
  shortTitle: string;
  coverage: string[];
  icon: string;
};

export const topics: Topic[] = [
  { id: "living", level: "P3", theme: "Diversity", title: "Diversity of living and non-living things", shortTitle: "Living things", icon: "🌱", coverage: ["characteristics of living things", "classification", "plants, animals, fungi and bacteria", "observable similarities and differences"] },
  { id: "materials", level: "P3", theme: "Diversity", title: "Diversity of materials", shortTitle: "Materials", icon: "🧱", coverage: ["strength", "flexibility", "float or sink", "waterproofing", "light transmission", "choosing materials for a purpose"] },
  { id: "lifecycles", level: "P3", theme: "Cycles", title: "Cycles in plants and animals — life cycles", shortTitle: "Life cycles", icon: "🦋", coverage: ["stages of life cycles", "similarities and differences", "repeated patterns", "growth and reproduction"] },
  { id: "magnets", level: "P3", theme: "Interactions", title: "Interaction of forces — magnets", shortTitle: "Magnets", icon: "🧲", coverage: ["push and pull", "poles", "attraction and repulsion", "magnetic materials", "direction of a freely suspended magnet"] },
  { id: "plantparts", level: "P4", theme: "Systems", title: "Plant system — plant parts and functions", shortTitle: "Plant parts", icon: "🌿", coverage: ["roots", "stem", "leaves", "functions of plant parts", "part-function reasoning"] },
  { id: "digestion", level: "P4", theme: "Systems", title: "Human system — digestive system", shortTitle: "Digestion", icon: "🍎", coverage: ["mouth", "gullet", "stomach", "small intestine", "large intestine", "functions and sequence"] },
  { id: "matter", level: "P4", theme: "Cycles", title: "Cycles in matter and water — matter", shortTitle: "Matter", icon: "🧊", coverage: ["solids, liquids and gases", "melting", "freezing", "evaporation", "condensation", "changes of state"] },
  { id: "light", level: "P4", theme: "Energy", title: "Energy forms and uses — light", shortTitle: "Light", icon: "💡", coverage: ["light sources", "reflection", "seeing objects", "light travels in straight lines", "shadows", "variables affecting shadows"] },
  { id: "heat", level: "P4", theme: "Energy", title: "Energy forms and uses — heat", shortTitle: "Heat", icon: "🌡️", coverage: ["heat versus temperature", "heat flow", "gain and loss of heat", "expansion and contraction", "change of state", "conductors and insulators"] },
  { id: "reproduction", level: "P5", theme: "Cycles", title: "Cycles in plants and animals — reproduction", shortTitle: "Reproduction", icon: "🌼", coverage: ["cell as a basic unit of life", "pollination", "fertilisation", "seed dispersal", "germination", "continuity and inherited characteristics"] },
  { id: "water", level: "P5", theme: "Cycles", title: "Cycles in matter and water — water", shortTitle: "Water cycle", icon: "💧", coverage: ["three states of water", "freezing and boiling", "evaporation", "condensation", "water cycle", "factors affecting evaporation"] },
  { id: "planttransport", level: "P5", theme: "Systems", title: "Plant system — transport", shortTitle: "Plant transport", icon: "🌳", coverage: ["water-carrying tubes", "food-carrying tubes", "roots-to-plant water transport", "leaves-to-plant food transport", "transport investigations"] },
  { id: "humansystems", level: "P5", theme: "Systems", title: "Human respiratory and circulatory systems", shortTitle: "Human systems", icon: "🫁", coverage: ["air composition", "nose, windpipe and lungs", "heart, blood and blood vessels", "oxygen and carbon dioxide", "integration with digestion", "transport of substances"] },
  { id: "electricity", level: "P5", theme: "Systems", title: "Electrical system", shortTitle: "Electricity", icon: "🔋", coverage: ["circuit components", "closed circuits", "conductors and insulators", "batteries in series", "bulbs in series and parallel", "current reasoning"] },
  { id: "photosynthesis", level: "P6", theme: "Energy", title: "Energy forms and uses — photosynthesis", shortTitle: "Photosynthesis", icon: "☀️", coverage: ["requirements for photosynthesis", "food production", "oxygen and carbon dioxide", "chlorophyll", "light energy", "respiration releases energy from food"] },
  { id: "energy", level: "P6", theme: "Energy", title: "Energy conversion", shortTitle: "Energy conversion", icon: "⚡", coverage: ["kinetic energy", "potential energy", "light, heat, sound and electrical energy", "energy conversion chains", "Sun as an ultimate energy source", "energy conservation"] },
  { id: "forces", level: "P6", theme: "Interactions", title: "Interaction of forces", shortTitle: "Forces", icon: "🏹", coverage: ["force as push or pull", "frictional force", "gravitational force", "elastic spring force", "effects of forces", "variables in force investigations"] },
  { id: "environment", level: "P6", theme: "Interactions", title: "Interactions within the environment", shortTitle: "Environment", icon: "🌏", coverage: ["organism, population and community", "habitat", "food chains and food webs", "adaptations", "interdependence", "human impact and conservation"] }
];

export const questions: Question[] = [
  { id:"living-1",topicId:"living",concept:"Characteristics",difficulty:"foundation",stem:"Which observation gives the strongest evidence that something is living?",options:["It is green.","It moves when pushed.","It grows and reproduces.","It contains water."],correctIndex:2,explanation:"Growth and reproduction are life processes; colour or movement caused by a push are not enough.",trap:"Using a visible feature instead of a life process." },
  { id:"living-2",topicId:"living",concept:"Classification",difficulty:"application",stem:"A pupil groups a mushroom with plants because both stay in one place. What is the best correction?",options:["The grouping is correct.","Mushrooms are fungi, not plants.","Anything that does not walk is a plant.","Mushrooms are non-living."],correctIndex:1,explanation:"Mushrooms belong to fungi. Classification uses relevant shared characteristics, not one superficial feature.",trap:"Over-generalising from one characteristic." },
  { id:"living-3",topicId:"living",concept:"Response",difficulty:"application",stem:"A shoot bends towards a window over several days. Which characteristic is shown most directly?",options:["Reproduction","Response to surroundings","Need for food","Classification"],correctIndex:1,explanation:"The shoot changes its growth direction in response to light.",trap:"Choosing a true plant fact that does not match the observation." },
  { id:"living-4",topicId:"living",concept:"Broad groups",difficulty:"challenge",stem:"Which pair belongs to two different broad groups of living things?",options:["Mould and mushroom","Bird and fish","Yeast and mould","Bacterium and mushroom"],correctIndex:3,explanation:"A bacterium belongs to bacteria while a mushroom belongs to fungi.",trap:"Confusing animal subgroups with the broad groups." },

  { id:"materials-1",topicId:"materials",concept:"Choosing materials",difficulty:"foundation",stem:"Which property is most important for a raincoat?",options:["Waterproof","Magnetic","Good conductor of heat","Able to dissolve in water"],correctIndex:0,explanation:"A raincoat should prevent water passing through it.",trap:"Picking an irrelevant property." },
  { id:"materials-2",topicId:"materials",concept:"Light transmission",difficulty:"application",stem:"Material X allows some light through but objects behind it cannot be seen clearly. Which conclusion is safest?",options:["X allows no light through.","X allows some light through.","X must be glass.","X must float."],correctIndex:1,explanation:"The observation supports only that some light passes through X.",trap:"Inferring a property that was not tested." },
  { id:"materials-3",topicId:"materials",concept:"Fair test",difficulty:"application",stem:"Different material strips are tested for strength. What should be kept the same?",options:["Material","Whether they break","Size and shape of strips","Strength"],correctIndex:2,explanation:"Dimensions should be controlled while material type is changed.",trap:"Trying to keep the independent variable unchanged." },
  { id:"materials-4",topicId:"materials",concept:"Property and use",difficulty:"challenge",stem:"A hot-pot handle should preferably be made from a material that is...",options:["a good heat conductor","a poor heat conductor and strong enough","transparent only","magnetic"],correctIndex:1,explanation:"The handle should reduce heat transfer and remain strong in use.",trap:"Matching only one unsuitable property." },

  { id:"lifecycles-1",topicId:"lifecycles",concept:"Life-cycle stages",difficulty:"foundation",stem:"Which statement about life cycles is correct?",options:["Every animal has four stages.","A life cycle shows repeated stages from one generation to the next.","Only insects have life cycles.","Young always look like adults."],correctIndex:1,explanation:"Life cycles repeat across generations, but stages differ among organisms.",trap:"Assuming one familiar cycle applies to all organisms." },
  { id:"lifecycles-2",topicId:"lifecycles",concept:"Comparison",difficulty:"application",stem:"A butterfly and grasshopper both begin as eggs. What can definitely be concluded?",options:["Their whole cycles are identical.","Both have an egg stage.","Both have a pupa stage.","Their adults look alike."],correctIndex:1,explanation:"Only the shared egg stage is supported by the information.",trap:"Extending one similarity into a full similarity." },
  { id:"lifecycles-3",topicId:"lifecycles",concept:"Reproduction",difficulty:"application",stem:"Why is reproduction important in a life cycle?",options:["It makes individuals live forever.","It ensures continuity of the kind.","It prevents growth.","It stops variation."],correctIndex:1,explanation:"Reproduction produces a new generation so the kind can continue.",trap:"Confusing continuity of a kind with immortality." },
  { id:"lifecycles-4",topicId:"lifecycles",concept:"Sequence",difficulty:"challenge",stem:"An animal has egg → young → adult. After the adult reproduces, what stage comes next?",options:["Adult","Egg","Young","The cycle stops"],correctIndex:1,explanation:"Reproduction begins the next generation at the egg stage.",trap:"Reading a cycle as a line that ends." },

  { id:"magnets-1",topicId:"magnets",concept:"Poles",difficulty:"foundation",stem:"What happens when two north poles are brought together?",options:["Attract","Repel","Nothing","Both lose magnetism"],correctIndex:1,explanation:"Like poles repel; unlike poles attract.",trap:"Remembering only that magnets can attract." },
  { id:"magnets-2",topicId:"magnets",concept:"Magnetic materials",difficulty:"application",stem:"A magnet attracts an object. Which conclusion is justified?",options:["The object is definitely a magnet.","It is made of or contains magnetic material.","It must be aluminium.","It has one pole."],correctIndex:1,explanation:"Magnetic materials are attracted by magnets; attraction does not prove the object is itself a magnet.",trap:"Treating attraction as proof of magnetism." },
  { id:"magnets-3",topicId:"magnets",concept:"Sure test",difficulty:"challenge",stem:"Which observation proves an unknown bar is a magnet rather than just magnetic material?",options:["It is attracted to a magnet.","It repels one pole of a known magnet.","It is metal.","It sinks."],correctIndex:1,explanation:"Repulsion is the sure test for a magnet.",trap:"Using attraction as the sure test." },
  { id:"magnets-4",topicId:"magnets",concept:"Direction",difficulty:"application",stem:"A freely suspended bar magnet comes to rest roughly in which direction?",options:["East-west","North-south","Straight down","Towards any metal"],correctIndex:1,explanation:"A freely suspended magnet aligns roughly north-south.",trap:"Mixing magnetic direction with gravity." },

  { id:"plantparts-1",topicId:"plantparts",concept:"Roots",difficulty:"foundation",stem:"Which is a main function of roots?",options:["Absorb water from soil","Make seeds directly","Reflect light","Pump blood"],correctIndex:0,explanation:"Roots absorb water and help anchor the plant.",trap:"Assigning another organ's function to roots." },
  { id:"plantparts-2",topicId:"plantparts",concept:"Leaves",difficulty:"application",stem:"Most leaves are removed from a plant. Which function is affected most directly?",options:["Absorbing water from soil","Making food","Anchoring","Holding soil only"],correctIndex:1,explanation:"Leaves are the main sites of photosynthesis and food-making.",trap:"Confusing absorption with food production." },
  { id:"plantparts-3",topicId:"plantparts",concept:"Stem",difficulty:"application",stem:"Why can stem damage affect both leaves and roots?",options:["The stem contains transport pathways.","The stem makes all water.","The stem is the only part taking in air.","The stem changes soil into food."],correctIndex:0,explanation:"The stem supports transport between roots, leaves and other parts.",trap:"Giving one plant part every function." },
  { id:"plantparts-4",topicId:"plantparts",concept:"System effect",difficulty:"challenge",stem:"Plant B has badly damaged roots while a similar Plant A has healthy roots. What is most likely?",options:["B may wilt because water uptake is reduced.","B receives more water.","A stops making food.","Both must grow equally."],correctIndex:0,explanation:"Root damage reduces water absorption and can cause wilting.",trap:"Ignoring how one part affects the whole system." },

  { id:"digestion-1",topicId:"digestion",concept:"Sequence",difficulty:"foundation",stem:"Which sequence is correct?",options:["mouth → stomach → gullet → small intestine","mouth → gullet → stomach → small intestine","mouth → lungs → stomach","mouth → heart → stomach"],correctIndex:1,explanation:"Food passes mouth → gullet → stomach → small intestine.",trap:"Mixing organs from different systems." },
  { id:"digestion-2",topicId:"digestion",concept:"Small intestine",difficulty:"application",stem:"Digested food enters the bloodstream mainly through which organ?",options:["Small intestine","Windpipe","Large intestine only","Nose"],correctIndex:0,explanation:"Digested food is absorbed mainly through the small intestine.",trap:"Confusing digestion with breathing." },
  { id:"digestion-3",topicId:"digestion",concept:"Large intestine",difficulty:"application",stem:"What is a key role of the large intestine?",options:["Absorb water from undigested matter","Pump blood","Take oxygen into blood","Make food"],correctIndex:0,explanation:"The large intestine absorbs water from undigested matter.",trap:"Choosing a function from another body system." },
  { id:"digestion-4",topicId:"digestion",concept:"System integration",difficulty:"challenge",stem:"After a meal, why is the circulatory system important?",options:["It transports absorbed digested food to cells.","It chews food.","It pushes food down the gullet.","It turns food into oxygen."],correctIndex:0,explanation:"The blood transports absorbed digested food to body cells.",trap:"Thinking body systems work independently." },

  { id:"matter-1",topicId:"matter",concept:"States",difficulty:"foundation",stem:"Which property best distinguishes a liquid from a solid?",options:["A liquid has fixed shape.","A liquid takes the shape of its container.","A liquid has no mass.","A liquid cannot be seen."],correctIndex:1,explanation:"A liquid has a definite volume but takes the shape of its container.",trap:"Confusing shape with volume." },
  { id:"matter-2",topicId:"matter",concept:"Condensation",difficulty:"application",stem:"Water droplets form outside a cold cup. Where did they mainly come from?",options:["Water leaked through the cup.","Water vapour in air condensed.","Coldness became water.","The cup produced water."],correctIndex:1,explanation:"Water vapour in surrounding air loses heat and condenses on the cold surface.",trap:"Assuming the water came from inside the cup." },
  { id:"matter-3",topicId:"matter",concept:"Evaporation",difficulty:"application",stem:"A wet floor dries without boiling. Which process explains this?",options:["Freezing","Evaporation","Condensation","Melting"],correctIndex:1,explanation:"Evaporation occurs at the liquid surface below boiling point.",trap:"Thinking liquid becomes gas only by boiling." },
  { id:"matter-4",topicId:"matter",concept:"Change of state",difficulty:"challenge",stem:"Ice melts in a warm room. Which statement is correct?",options:["Solid water becomes liquid water.","A new substance forms.","Gas becomes liquid.","Water particles disappear."],correctIndex:0,explanation:"Melting changes state but the substance remains water.",trap:"Treating a state change as formation of a new substance." },

  { id:"light-1",topicId:"light",concept:"Seeing",difficulty:"foundation",stem:"Why can we see a non-luminous book in a bright room?",options:["The book makes light.","Light reflected from it enters our eyes.","Our eyes send light to it.","Sound enters our eyes."],correctIndex:1,explanation:"Light from a source reflects from the book into our eyes.",trap:"Reversing the direction of light." },
  { id:"light-2",topicId:"light",concept:"Straight-line travel",difficulty:"application",stem:"A candle is seen through three cards only when their holes line up. What does this show?",options:["Light travels in straight lines.","Light always bends around cards.","Sound is faster.","The candle is magnetic."],correctIndex:0,explanation:"The aligned holes create a straight path for light to the eye.",trap:"Choosing an unrelated observation." },
  { id:"light-3",topicId:"light",concept:"Shadow size",difficulty:"application",stem:"A toy is moved closer to a lamp while the screen stays fixed. What usually happens to its shadow?",options:["It becomes larger.","It disappears.","It becomes a light source.","Its colour matches the toy."],correctIndex:0,explanation:"Closer to the source, the toy blocks a wider spread of rays, making a larger shadow.",trap:"Ignoring which distance changed." },
  { id:"light-4",topicId:"light",concept:"Fair test",difficulty:"challenge",stem:"To test how lamp distance affects shadow size, which variable should be changed?",options:["Lamp-object distance","Shape and distance together","Screen and object together","Brightness and object size together"],correctIndex:0,explanation:"Change one independent variable while keeping other relevant factors constant.",trap:"Changing several variables at once." },

  { id:"heat-1",topicId:"heat",concept:"Heat vs temperature",difficulty:"foundation",stem:"Which statement is correct?",options:["Heat and temperature are identical.","Heat is energy; temperature measures how hot or cold something is.","Temperature flows.","Coldness is energy."],correctIndex:1,explanation:"Heat is energy transfer; temperature measures degree of hotness.",trap:"Using heat and temperature as synonyms." },
  { id:"heat-2",topicId:"heat",concept:"Heat flow",difficulty:"application",stem:"A 25°C spoon is placed in 70°C soup. Initially heat flows...",options:["spoon to soup","soup to spoon","with no net change","from air only"],correctIndex:1,explanation:"Heat flows from hotter to colder regions.",trap:"Thinking 'cold' flows into a hotter object." },
  { id:"heat-3",topicId:"heat",concept:"Conductors",difficulty:"application",stem:"Why are metal cooking pots useful for heating food?",options:["Metal is a good heat conductor.","Metal stops heat transfer.","Metal creates coldness.","Metal is transparent."],correctIndex:0,explanation:"Metal conducts heat effectively from the source to the food.",trap:"Confusing pot-body and handle requirements." },
  { id:"heat-4",topicId:"heat",concept:"Expansion",difficulty:"challenge",stem:"A tight metal lid becomes easier to open after warm water is run over it. Why?",options:["The lid can expand when heated.","The jar becomes magnetic.","All friction disappears.","The lid contracts immediately."],correctIndex:0,explanation:"Heating can cause solids to expand slightly.",trap:"Selecting a familiar word without linking cause and effect." },

  { id:"reproduction-1",topicId:"reproduction",concept:"Pollination",difficulty:"foundation",stem:"Pollination is the transfer of pollen grains from...",options:["anther to stigma","stigma to roots","ovary to leaf","seed to fruit"],correctIndex:0,explanation:"Pollination transfers pollen from anther to stigma.",trap:"Confusing pollination with fertilisation." },
  { id:"reproduction-2",topicId:"reproduction",concept:"Fertilisation",difficulty:"application",stem:"Which event describes fertilisation?",options:["A seed is dispersed.","A male reproductive cell fuses with a female reproductive cell.","A flower opens.","A fruit falls."],correctIndex:1,explanation:"Fertilisation is the fusion of male and female reproductive cells.",trap:"Calling any reproductive stage fertilisation." },
  { id:"reproduction-3",topicId:"reproduction",concept:"Germination",difficulty:"application",stem:"Which conditions are generally needed for germination?",options:["Water, air and suitable temperature","Light only","Soil only","Carbon dioxide and darkness only"],correctIndex:0,explanation:"Seeds generally need water, oxygen and a suitable temperature.",trap:"Mixing germination requirements with photosynthesis." },
  { id:"reproduction-4",topicId:"reproduction",concept:"Inheritance",difficulty:"challenge",stem:"A young animal resembles both parents but is not identical to either. What is supported?",options:["Characteristics can be passed from parents.","Offspring are always identical to one parent.","Reproduction prevents variation.","Only plants inherit traits."],correctIndex:0,explanation:"Offspring often inherit characteristics while still showing variation.",trap:"Turning resemblance into exact identity." },

  { id:"water-1",topicId:"water",concept:"Freezing point",difficulty:"foundation",stem:"Pure water freezes at about...",options:["0°C","25°C","50°C","100°C"],correctIndex:0,explanation:"Under standard primary-science conditions, water freezes at about 0°C.",trap:"Swapping freezing and boiling points." },
  { id:"water-2",topicId:"water",concept:"Evaporation factors",difficulty:"application",stem:"Which change usually makes wet clothes dry faster?",options:["Moving air passes over them.","Fold them into a pile.","Cool still air.","Cover with waterproof sheet."],correctIndex:0,explanation:"Moving air removes water vapour near the clothes and increases evaporation rate.",trap:"Choosing a change that traps water vapour." },
  { id:"water-3",topicId:"water",concept:"Water cycle",difficulty:"application",stem:"Which pair of processes moves water between Earth's surface and clouds?",options:["Evaporation and condensation","Melting and magnetism","Digestion and respiration","Friction and reflection"],correctIndex:0,explanation:"Water evaporates, then water vapour condenses into tiny droplets in clouds.",trap:"Selecting unrelated processes." },
  { id:"water-4",topicId:"water",concept:"Fair test",difficulty:"challenge",stem:"A pupil compares evaporation from a wide dish and narrow cup. What should be kept the same?",options:["Exposed surface area","Container shape","Starting amount of water and surrounding conditions","Rate of evaporation"],correctIndex:2,explanation:"If surface area is being compared, starting water amount and surroundings should be controlled.",trap:"Keeping the independent variable unchanged." },

  { id:"planttransport-1",topicId:"planttransport",concept:"Water transport",difficulty:"foundation",stem:"Water absorbed by roots is transported mainly...",options:["through water-carrying tubes to other parts","back into soil only","directly to seeds only","through air outside the stem"],correctIndex:0,explanation:"Water-carrying tubes transport water from roots to other plant parts.",trap:"Ignoring the internal transport system." },
  { id:"planttransport-2",topicId:"planttransport",concept:"Food transport",difficulty:"application",stem:"Food made in leaves must reach roots. Which structures are most directly involved?",options:["Food-carrying tubes","Root hairs only","Petals","Soil"],correctIndex:0,explanation:"Food-carrying tubes transport food from leaves to other parts.",trap:"Assuming plant food comes from soil." },
  { id:"planttransport-3",topicId:"planttransport",concept:"Evidence",difficulty:"application",stem:"A white flower stem sits in coloured water; later coloured lines appear in stem and petals. What does this support?",options:["Water travels through plant pathways.","Food is made in roots.","Petals pump like a heart.","The plant is non-living."],correctIndex:0,explanation:"The coloured water traces water transport pathways through the plant.",trap:"Claiming more than the observation shows." },
  { id:"planttransport-4",topicId:"planttransport",concept:"System failure",difficulty:"challenge",stem:"Food-carrying tubes are badly damaged but water-carrying tubes still work. What is most direct?",options:["Food may not reach some parts effectively.","Roots cannot absorb any water.","Light stops travelling straight.","The plant instantly becomes non-living."],correctIndex:0,explanation:"Damage to food-carrying tubes interferes specifically with food transport.",trap:"Assuming damage to one pathway stops every process." },

  { id:"humansystems-1",topicId:"humansystems",concept:"Respiratory pathway",difficulty:"foundation",stem:"Which sequence correctly shows the main air pathway?",options:["nose → windpipe → lungs","nose → stomach → lungs","mouth → heart → lungs","lungs → gullet → stomach"],correctIndex:0,explanation:"Air enters through the nose and travels down the windpipe to the lungs.",trap:"Mixing digestive and respiratory pathways." },
  { id:"humansystems-2",topicId:"humansystems",concept:"Blood transport",difficulty:"application",stem:"Which substance is transported by blood from lungs to body cells?",options:["Oxygen","Undigested food","Soil","Light"],correctIndex:0,explanation:"Blood transports oxygen from lungs to body cells.",trap:"Selecting material outside the circulatory system." },
  { id:"humansystems-3",topicId:"humansystems",concept:"Integration",difficulty:"application",stem:"Why must digestive, respiratory and circulatory systems work together?",options:["Cells need transported digested food and oxygen.","They all do the same job.","Lungs digest food.","The heart makes oxygen."],correctIndex:0,explanation:"Digestion supplies nutrients, respiration supplies oxygen and blood transports them.",trap:"Assigning one system another system's function." },
  { id:"humansystems-4",topicId:"humansystems",concept:"Respiration",difficulty:"challenge",stem:"Which statement is correct about humans, plants and fish?",options:["All can take in oxygen and give out carbon dioxide during respiration.","Only humans need oxygen.","Plants never give out carbon dioxide.","Fish obtain oxygen only on land."],correctIndex:0,explanation:"Living things respire, though gas-exchange structures differ.",trap:"Confusing photosynthesis with absence of respiration." },

  { id:"electricity-1",topicId:"electricity",concept:"Closed circuit",difficulty:"foundation",stem:"A bulb lights only when the circuit is...",options:["closed and complete","open at the switch","missing a wire","made only of insulators"],correctIndex:0,explanation:"Current needs a complete conducting path.",trap:"Thinking a battery alone is sufficient." },
  { id:"electricity-2",topicId:"electricity",concept:"Conductors",difficulty:"application",stem:"A test material replaces part of a wire and the bulb still lights. What can be inferred?",options:["It conducts electricity in this setup.","It must be a magnet.","It must be transparent.","It cannot contain metal."],correctIndex:0,explanation:"If current passes through the material, it acts as a conductor in the setup.",trap:"Inferring unrelated material properties." },
  { id:"electricity-3",topicId:"electricity",concept:"Batteries in series",difficulty:"application",stem:"In a simple one-bulb circuit, adding another identical battery in series usually makes the bulb...",options:["brighter","always go out","become an insulator","produce no energy conversion"],correctIndex:0,explanation:"Additional identical batteries in series usually increase current and brightness in this simple comparison.",trap:"Treating every added component as extra resistance." },
  { id:"electricity-4",topicId:"electricity",concept:"Series vs parallel",difficulty:"challenge",stem:"Compared with two identical bulbs in series on the same battery, bulbs in parallel are generally...",options:["brighter","always dimmer","unable to light","not part of a circuit"],correctIndex:0,explanation:"In the primary-science comparison, identical bulbs in parallel are generally brighter than in series.",trap:"Counting bulbs without considering connection." },

  { id:"photosynthesis-1",topicId:"photosynthesis",concept:"Food production",difficulty:"foundation",stem:"Which statement about plant food is correct?",options:["Plants make food in green parts by photosynthesis.","Plants absorb ready-made food from soil.","Sunlight itself is food.","Water alone becomes all food."],correctIndex:0,explanation:"Plants make food using light energy, water and carbon dioxide in green parts.",trap:"Calling sunlight or soil nutrients 'food'." },
  { id:"photosynthesis-2",topicId:"photosynthesis",concept:"Requirements",difficulty:"application",stem:"Part of a destarched leaf is covered so light cannot reach it. What factor is being tested?",options:["Whether light is needed for photosynthesis","Whether roots absorb water","Whether gravity exists","Whether leaves are magnetic"],correctIndex:0,explanation:"The covered area changes light exposure while other conditions can remain similar.",trap:"Naming a true plant process the setup does not test." },
  { id:"photosynthesis-3",topicId:"photosynthesis",concept:"Gases",difficulty:"application",stem:"During photosynthesis, a green plant uses ___ and releases ___.",options:["carbon dioxide; oxygen","oxygen; carbon dioxide only","nitrogen; heat","water vapour; soil"],correctIndex:0,explanation:"Photosynthesis uses carbon dioxide and releases oxygen.",trap:"Swapping photosynthesis and respiration." },
  { id:"photosynthesis-4",topicId:"photosynthesis",concept:"Respiration",difficulty:"challenge",stem:"Which statement correctly links photosynthesis and respiration?",options:["Photosynthesis makes food; respiration releases energy from food.","Respiration occurs only in animals.","Photosynthesis releases energy from food in lungs.","Plants stop respiring in light."],correctIndex:0,explanation:"Photosynthesis makes food; respiration releases energy from food in living things.",trap:"Believing plants photosynthesise instead of respiring." },

  { id:"energy-1",topicId:"energy",concept:"Energy forms",difficulty:"foundation",stem:"A moving bicycle has mainly which energy because it is moving?",options:["Kinetic energy","Light only","Sound only","No energy"],correctIndex:0,explanation:"Kinetic energy is associated with movement.",trap:"Choosing a side-effect instead of the asked energy form." },
  { id:"energy-2",topicId:"energy",concept:"Energy conversion",difficulty:"application",stem:"In a battery torch, the useful output is mainly...",options:["light energy","gravitational force","food","water"],correctIndex:0,explanation:"Stored energy is converted through electrical energy to light, with some heat.",trap:"Naming a force or substance instead of energy." },
  { id:"energy-3",topicId:"energy",concept:"Sun as source",difficulty:"application",stem:"Which chain best shows how Sun energy can eventually help a child run?",options:["Sun → plant food → child → movement","Sun → magnet → water → child","Sun → gravity disappears → child","Sun → soil becomes food → child"],correctIndex:0,explanation:"Plants capture light energy in food; food energy supports movement after respiration.",trap:"Skipping food and respiration." },
  { id:"energy-4",topicId:"energy",concept:"Conservation",difficulty:"challenge",stem:"Why switch off unused electrical appliances?",options:["It reduces unnecessary use of energy resources.","It stops all energy existing.","It makes electricity a force.","It increases wasted conversion."],correctIndex:0,explanation:"Reducing unnecessary electricity use reduces demand on energy resources.",trap:"Confusing conservation with making energy disappear." },

  { id:"forces-1",topicId:"forces",concept:"Force",difficulty:"foundation",stem:"A force is best described as...",options:["a push or pull","a form of matter","a type of light","a temperature"],correctIndex:0,explanation:"At primary level, a force is a push or pull.",trap:"Mixing force with energy or matter." },
  { id:"forces-2",topicId:"forces",concept:"Friction",difficulty:"application",stem:"Why do bicycle brakes slow the bicycle?",options:["They increase friction opposing motion.","They remove gravity.","They create kinetic energy.","They make it weightless."],correctIndex:0,explanation:"Brakes increase friction that opposes motion.",trap:"Thinking friction always speeds things up." },
  { id:"forces-3",topicId:"forces",concept:"Gravity",difficulty:"application",stem:"A ball is thrown upward. Which force acts throughout its flight?",options:["Gravitational force","Magnetic force only while falling","Elastic force","No force at the top"],correctIndex:0,explanation:"Earth's gravitational force acts throughout the ball's flight.",trap:"Thinking a force exists only when motion is in its direction." },
  { id:"forces-4",topicId:"forces",concept:"Fair test",difficulty:"challenge",stem:"Which investigation best tests how load affects spring extension?",options:["Use identical springs and vary only load.","Change spring and load together.","Use different lengths and loads.","Measure spring colour."],correctIndex:0,explanation:"A fair test varies load while keeping spring type and setup constant.",trap:"Changing multiple variables." },

  { id:"environment-1",topicId:"environment",concept:"Food chains",difficulty:"foundation",stem:"In grass → grasshopper → frog → snake, which gets energy directly from the grasshopper?",options:["Grass","Frog","Snake","All equally"],correctIndex:1,explanation:"The arrow shows food energy moving from grasshopper to frog.",trap:"Reading food-chain arrows backwards." },
  { id:"environment-2",topicId:"environment",concept:"Population",difficulty:"application",stem:"Which describes a population?",options:["All living and non-living things in a pond","All frogs of the same kind in one pond","One frog and one fish","Every habitat on Earth"],correctIndex:1,explanation:"A population is organisms of the same kind living in the same area.",trap:"Confusing population with community or habitat." },
  { id:"environment-3",topicId:"environment",concept:"Interdependence",difficulty:"application",stem:"If most insects in an area disappear, what immediate effect is most plausible?",options:["Animals feeding mainly on those insects may have less food.","All plants instantly die.","Gravity weakens.","The water cycle stops."],correctIndex:0,explanation:"A large fall in prey can reduce food available to predators.",trap:"Choosing an unsupported extreme effect." },
  { id:"environment-4",topicId:"environment",concept:"Conservation",difficulty:"challenge",stem:"A wetland is drained for roads. Which consequence is most directly linked to habitat loss?",options:["Some organisms lose food, shelter or breeding places.","All organisms everywhere go extinct.","The Sun gives less light.","Water can no longer evaporate."],correctIndex:0,explanation:"Habitat loss removes resources and conditions needed by local organisms.",trap:"Turning a local effect into a global absolute." }
];

export const sprintPlan = [
  { day:1,title:"Baseline Mission",task:"30-question diagnostic mock",focus:"Find the exact MCQ leak points before revising." },
  { day:2,title:"P3 Accuracy Reset",task:"Living things + Materials",focus:"Classification, evidence and properties for purpose." },
  { day:3,title:"P3 Patterns",task:"Life cycles + Magnets",focus:"Sequence, attraction/repulsion and the sure test." },
  { day:4,title:"P4 Systems",task:"Plant parts + Digestion",focus:"Part → function → effect if the part fails." },
  { day:5,title:"P4 Physical Science",task:"Matter + Light + Heat",focus:"Condensation, shadow logic, heat vs temperature." },
  { day:6,title:"P5 Cycles",task:"Reproduction + Water",focus:"Do not mix pollination/fertilisation or evaporation/boiling." },
  { day:7,title:"P5 Transport",task:"Plant + Human systems",focus:"Track substances: where they start, go and why." },
  { day:8,title:"Electricity Lab",task:"Circuits + mixed questions",focus:"Closed paths, conductors, batteries, series and parallel." },
  { day:9,title:"P6 Energy",task:"Photosynthesis + Energy conversion",focus:"Food is not sunlight; track each conversion." },
  { day:10,title:"P6 Forces",task:"Forces + Environment",focus:"Cause-effect relationships and food-web evidence." },
  { day:11,title:"Trap Lab",task:"Mixed distractor drill",focus:"NOT, always/never, partial truths and irrelevant options." },
  { day:12,title:"Evidence Day",task:"Experiment and data-style MCQs",focus:"Independent variable, controls, observation vs inference." },
  { day:13,title:"Weak Spot Rescue I",task:"Auto-selected weakest topics",focus:"Repair misconceptions, not just scores." },
  { day:14,title:"Weak Spot Rescue II",task:"Second weakest-topic cycle",focus:"Correct guesses still count as weak." },
  { day:15,title:"Timed Mock I",task:"30 questions / 45 minutes",focus:"Use predict → eliminate → prove." },
  { day:16,title:"Timed Mock II",task:"30 questions + journal review",focus:"Target ≥27/30 with reasons, not lucky guesses." },
  { day:17,title:"Misconception Sweep",task:"Journal + 20-question rescue",focus:"Re-answer recurring traps from memory." },
  { day:18,title:"Calm Final Run",task:"30-question full MCQ simulation",focus:"Accuracy first, pace second, no panic clicking." }
];
