import type { StudentInput } from './types';

export function storedStudentToInput(student: Record<string, any>): StudentInput {
  const programmeLevel: 'undergraduate' | 'postgraduate' =
    student.desired_program_level === 'postgraduate' ? 'postgraduate' : 'undergraduate';

  return {
    id: student.id,
    programLevel: programmeLevel,
    firstName: student.first_name,
    lastName: student.last_name,
    email: student.email || undefined,
    phone: student.phone || undefined,
    yearX: student.year_x,
    marksX: student.marks_x,
    yearXii: student.year_xii,
    marksXii: student.marks_xii,
    board: student.board || undefined,
    city: student.city || undefined,
    state: student.state || undefined,
    country: student.country || 'India',
    targetIntake: student.target_intake || undefined,
    subjectsInterest: student.subjects_interest || [],
    preferredLocations: student.preferred_locations || [],
    budgetMin: student.budget_min,
    budgetMax: student.budget_max,
    salaryExpectation: student.salary_expectation,
    hostelRequired: Boolean(student.hostel_required),
    passion: student.passion || undefined,
    purpose: student.purpose || undefined,
    strengths: student.strengths || undefined,
    constraints: student.constraints || undefined,
    careerGoals: student.career_goals || undefined,
    supportRequired: student.support_required || [],
    notes: student.notes || undefined,
    linkedinUrl: student.linkedin_url || undefined,
    linkedinProfileText: student.linkedin_profile_text || undefined,
    linkedinProfilePdfText: student.linkedin_profile_pdf_text || undefined,
    facebookUrl: student.facebook_url || undefined,
    instagramUrl: student.instagram_url || undefined,
    xUrl: student.x_url || undefined,
    portfolioUrl: student.portfolio_url || undefined,
    accolades: student.accolades || undefined,
    extracurricularActivities: student.extracurricular_activities || undefined,
    rewards: student.rewards || undefined,
    specialSkills: student.special_skills || undefined,
    certifications: student.certifications || undefined,
    languages: student.languages || undefined,
    workExperience: student.work_experience || undefined,
    resumeText: student.resume_text || undefined,
    resumeFileText: student.resume_file_text || undefined,
    undergraduateDegree: student.undergraduate_degree || undefined,
    undergraduateSpecialisation: student.undergraduate_specialisation || undefined,
    undergraduateUniversity: student.undergraduate_university || undefined,
    undergraduateGraduationYear: student.undergraduate_graduation_year,
    pgApplicantStatus: student.pg_applicant_status || undefined,
    semestersCompleted: student.semesters_completed,
    semesterMarks: student.semester_marks || {},
    undergraduateFinalPercentage: student.undergraduate_final_percentage,
    currentEmployer: student.current_employer || undefined,
    currentJobTitle: student.current_job_title || undefined,
    workExperienceMonths: student.work_experience_months
  };
}
